### ISSUE TITLE
Can't get it to work properly

### ISSUE THREAD

**Issue by KonstantinSchuette** [bin101/SFBotJ#2]
Hello,

I came across your project but sadly its discontinued. I would like to improve it, but can't get it to work. The program starts up nicely but after I've loaded my account with the server (w36.sfgame.net) and pressed start, nothing happens.

Would it at least be possible that you could help me getting it running?

**Comment by bin101** [comment]
The main issue will be that the API have changed very much since I discontinued it.
I am very sorry but I don't have the time to help you.
